module Datos(Comando(..),
            Lugar(..),
            Objeto(..),
            Mensaje,
            Direccion,
            PlazaDestino,
            AeropuertoDestino,
            ObjetoNombre,
            Estado,
            Ubicaciones,
            aeropuertos,
            comandos,
            lugares,
            objetos,
            ubicaciones)where

data Comando = Comando { clave::String, opciones::[String] } deriving(Show)
comandos::[Comando]
comandos = [
    Comando "n" ["n", "norte", "arriba"],
    Comando "s" ["s", "sur", "abajo"],
    Comando "e" ["e", "este", "derecha"],
    Comando "o" ["o", "oeste", "izquierda"]]

type Mensaje = String
type Direccion = String
type PlazaDestino = String
type AeropuertoDestino = String
type ObjetoNombre = String
type Estado = String


data Lugar = Plaza {nombre::String, rutas::[(Direccion, PlazaDestino)]}|
             Aeropuerto {nombre::String, rutas::[(Direccion, PlazaDestino)],vuelos::[AeropuertoDestino]} deriving (Show)

lugares::[Lugar]
lugares = [
    --Argentina
    Plaza "Mi Club Oficina director" [("s",  "Mi Club Oficina manager")],
    Plaza "Mi Club Oficina manager" [("n", "Mi Club Oficina director"),
                             ("e", "AeropuertoArgentina")],
    Aeropuerto "AeropuertoArgentina" [  ("o", "Mi Club Oficina manager"),
                                ("e","Club River Plate"),
                                ("n","Club Boca Juniors"),
                                ("s","Mercado Argentina")]
                                ["AeropuertoBrasil", "AeropuertoColombia","AeropuertoInglaterra","AeropuertoEspana","AeropuertoItalia","AeropuertoJapon"],
    Plaza "Mercado Argentina" [("n","AeropuertoArgentina")],
    Plaza "Club River Plate" [("o","AeropuertoArgentina"),
                                ("e","River Plate oficina manager")],
    Plaza "River Plate oficina manager" [("o","Club River Plate")],
    Plaza "Club Boca Juniors" [("s","AeropuertoArgentina"),
                                ("e","Boca Juniors oficina manager")],
    Plaza "Boca Juniors oficina manager" [("o","Club Boca Juniors")],
    --Brasil
    Aeropuerto "AeropuertoBrasil" [("e","Club Sao Paulo"),
                                ("o","Mercado Brasil")]
                                 ["AeropuertoColombia","AeropuertoArgentina","AeropuertoJapon","AeropuertoInglaterra"],
    Plaza "Mercado Brasil" [("e","AeropuertoBrasil")],
    Plaza "Club Sao Paulo" [("n", "Club Corinthians"),
                            ("o", "AeropuertoBrasil"),
                            ("e", "Sao Paulo oficina manager")],
    Plaza "Sao Paulo oficina manager" [("o","Club Sao Paulo")],
    Plaza "Club Corinthians" [("n", "Club Flamengo"),
                            ("o", "Centro de Negocio Brasil"),
                            ("e", "Corinthians oficina manager"),
                            ("s","Club Sao Paulo")],
    Plaza "Centro de Negocio Brasil" [("e","Club Corinthians")],
    Plaza "Corinthians oficina manager" [("o","Club Corinthians")],
    Plaza "Club Flamengo" [ ("o","Playa Brasil"),
                            ("e","Flamengo oficina manager"),
                            ("n","AeropuertoBrasilX"),
                            ("s","Club Corinthians")],
    Plaza "Playa Brasil" [("e","Club Flamengo")],
    Plaza "Flamengo oficina manager" [("o","Club Flamengo")],
    Aeropuerto "AeropuertoBrasilX"   [   ("n","Club Santos"),
                                    ("s","Club Flamengo")]
                                ["AeropuertoBrasil","AeropuertoColombia","AeropuertoItalia","AeropuertoChina"],
    Plaza "Club Santos" [   ("n","Santos oficina manager"),
                            ("s","AeropuertoBrasilX")],
    Plaza "Santos oficina manager" [ ("s","Club Santos")],
    --Colombia
    Aeropuerto "AeropuertoColombia"[("e","Plaza Colombia")] ["AeropuertoArgentina","AeropuertoBrasil","AeropuertoBrasilX","AeropuertoJapon","AeropuertoItalia"],
    Plaza "Plaza Colombia" [("o","AeropuertoColombia"),
                            ("e","Club Tolima"),
                            ("s","Club Junior"),
                            ("n","Mercado Colombia")],
    Plaza "Mercado Colombia" [("s","Plaza Colombia")],
    Plaza "Club Junior" [   ("e","Junior oficina manager"),
                            ("n","Plaza Colombia")],
    Plaza "Junior oficina manager" [ ("o","Club Junior")],
    Plaza "Club Tolima" [   ("n","Club Millonarios"),
                            ("e","Tolima oficina manager"),
                            ("o","Plaza Colombia")], 
    Plaza "Tolima oficina manager" [("o","Club Tolima")],  
    Plaza "Club Millonarios" [ ("s","Club Tolima"),
                                ("e","Millonarios oficina manager")],
    Plaza "Millonarios oficina manager" [("o","Club Millonarios")],
    --España
    Plaza "Barcelona oficina manager" [("s","Club Barcelona")],
    Plaza "Club Barcelona" [("n","Barcelona oficina manager"),
                            ("s","AeropuertoEspana")],
    Aeropuerto "AeropuertoEspana" [("n","Club Barcelona"),
                            ("e","Club Valencia"),
                            ("s","Plaza Madrid")]
                            ["AeropuertoBrasil", "AeropuertoColombia","AeropuertoArgentina","AeropuertoItalia","AeropuertoChina","AeropuertoJapon"],
    Plaza "Club Valencia" [ ("n","Plaza Valencia"),
                            ("e","Valencia oficina manager"),
                            ("o","AeropuertoEspana")],
    Plaza "Plaza Valencia"[ ("s","Club Valencia"),
                            ("n","Mercado Espana")],
    Plaza "Mercado Espana" [("s","Plaza Valencia")],
    Plaza "Valencia oficina manager" [("o","Club Valencia")],
    Plaza "Plaza Madrid" [ ("n","AeropuertoEspana"),
                            ("s","Ciudad de Sevilla"),
                            ("o","Club Real Madrid"),
                            ("e","Club Athletico de Madrid")],
    Plaza "Club Real Madrid" [("o","Real Madrid oficina manager"),
                                ("e","Plaza Madrid")],
    Plaza "Real Madrid oficina manager" [("e","Club Real Madrid")],
    Plaza "Club Athletico de Madrid" [("e","Athletico de Madrid oficina manager"),
                                        ("o","Plaza Madrid")],
    Plaza "Athletico de Madrid oficina manager" [("o","Club Athletico de Madrid")],
    Plaza "Ciudad de Sevilla" [("n","Plaza Madrid"),
                                ("e","Club Sevilla"),
                                ("s","Plaza Betis")],
    Plaza "Club Sevilla" [("e","Sevilla oficina manager"),
                            ("o","Ciudad de Sevilla"),
                            ("s","Club Betis")],
    Plaza "Sevilla oficina manager" [("o","Club Sevilla")],
    Plaza "Club Betis" [("s","Betis oficina manager"),
                        ("o","Plaza Betis"),
                        ("n","Club Sevilla")],
    Plaza "Betis oficina manager" [("n","Club Betis")],
    Plaza "Plaza Betis" [("n","Ciudad de Sevilla"),
                            ("e","Club Betis"),
                            ("s","Club Athletico Bilbao")],
    Plaza "Club Athletico Bilbao" [("n","Plaza Betis"),
                                    ("o","Athletico Bilbao oficina manager")],
    Plaza "Athletico Bilbao oficina manager" [("e","Club Athletico Bilbao")],
    --Japon
    Aeropuerto "AeropuertoJapon"[("e","Plaza Tokio"),
                            ("s","Mercado Japon")]
                             ["AeropuertoArgentina","AeropuertoBrasil","AeropuertoEspana","AeropuertoChina"],
    Plaza "Mercado Japon" [("n","AeropuertoJapon")],
    Plaza "Plaza Tokio" [("o","AeropuertoJapon"),
                            ("e","Club Tokio F.C"),
                            ("s","Club Yokohama")],
    Plaza "Club Tokio F.C" [   ("n","Club Kawasaki"),
                            ("e","Tokio F.C oficina manager"),
                            ("o","Plaza Tokio")],   
    Plaza "Tokio F.C oficina manager" [("o","Club Tokio F.C")],
    Plaza "Club Kawasaki" [ ("s","Club Tokio F.C"),
                                ("e","Kawasaki oficina manager")],
    Plaza "Kawasaki oficina manager" [("o","Club Kawasaki")],
    Plaza "Club Yokohama" [ ("n","Plaza Tokio"),
                                ("e","Yokohama oficina manager")],
    Plaza "Yokohama oficina manager" [("o","Club Yokohama")],
    --China
    Aeropuerto "AeropuertoChina" [  ("e","Club Shanghai"),
                            ("n","Club Jiangsu"),
                            ("s","Mercado China")]
                                ["AeropuertoBrasil", "AeropuertoColombia","AeropuertoEspana","AeropuertoArgentina","AeropuertoJapon"],
    Plaza "Mercado China" [("n","AeropuertoChina")],
    Plaza "Club Shanghai" [("o","AeropuertoChina"),
                                ("e","Shanghai oficina manager")],
    Plaza "Shanghai oficina manager" [("o","Club Shanghai")],
    Plaza "Club Jiangsu" [("s","AeropuertoChina"),
                                ("e","Jiangsu oficina manager")],
    Plaza "Jiangsu oficina manager" [("o","Club Jiangsu")],
    --Inglaterra
    Plaza "Manchester City oficina manager" [("s","Club Manchester City")],
    Plaza "Club Manchester City" [("n","Manchester City oficina manager"),
                            ("s","AeropuertoInglaterra")],
    Aeropuerto "AeropuertoInglaterra" [("n","Club Manchester City"),
                            ("e","Club Manchester United"),
                            ("s","Plaza Manchester")]
                            ["AeropuertoItalia", "AeropuertoColombia","AeropuertoArgentina"],
    Plaza "Club Manchester United" [ ("n","Ciudad Londres"),
                            ("e","Manchester United oficina manager"),
                            ("o","AeropuertoInglaterra")],
    Plaza "Ciudad Londres"[ ("s","Club Manchester United"),
                            ("n","Mercado Inglaterra")],
    Plaza "Mercado Inglaterra" [("s","Ciudad Londres")],
    Plaza "Manchester United oficina manager" [("o","Club Manchester United")],
    Plaza "Plaza Manchester" [ ("n","AeropuertoInglaterra"),
                            ("o","Club Chelsea")],
    Plaza "Club Chelsea" [("o","Chelsea oficina manager"),
                                ("e","Plaza Manchester")],
    Plaza "Chelsea oficina manager" [("e","Club Chelsea")],
    --Italia
    Aeropuerto "AeropuertoItalia"[("s","Mercado Italia")]["AeropuertoInglaterra","AeropuertoEspana","AeropuertoArgentina"],
    Plaza "Mercado Italia" [("n","AeropuertoItalia"),
                                ("e","Club Internacionale"),
                                ("s","Ciudad de Milan")],
    Plaza "Club Internacionale" [("e","Internacionale oficina manager"),
                            ("o","Mercado Italia"),
                            ("s","Club AC Milan")],
    Plaza "Internacionale oficina manager" [("o","Club Internacionale")],
    Plaza "Club AC Milan" [("s","AC Milan oficina manager"),
                        ("o","Ciudad de Milan"),
                        ("n","Club Internacionale")],
    Plaza "AC Milan oficina manager" [("n","Club AC Milan")],
    Plaza "Ciudad de Milan" [("n","Mercado Italia"),
                            ("e","Club AC Milan"),
                            ("s","Club Juventus")],
    Plaza "Club Juventus" [("n","Ciudad de Milan"),
                                    ("o","Juventus oficina manager")],
    Plaza "Juventus oficina manager" [("e","Club Juventus")]]

aeropuertos::[String]
aeropuertos = ["AeropuertoArgentina","AeropuertoBrasil","AeropuertoBrasilX", "AeropuertoColombia","AeropuertoJapon","AeropuertoEspana","AeropuertoChina","AeropuertoInglaterra","AeropuertoItalia"]


data Objeto = Persona {nombre_o::String}|
              Jugador {nombre_o::String, valor::Int, nivel::Int}|
              Sponsor {nombre_o::String, ingreso::Int} deriving (Show)

objetos::[Objeto]
objetos = [

    Sponsor "CocaCola" 1200,
    Sponsor "Adidas" 7000,
    Sponsor "Nike" 9100,
    Sponsor "Rakuten" 1900,
    Sponsor "FlyEmirates" 1700,
    Sponsor "Audi" 2100,
    Sponsor "Ford" 2000,
    Sponsor "EASport" 1900,
    --Jugadores
    Jugador "Luisito" 1000 2,
    Jugador "Luisinho" 3700 3,
    Jugador "Gambetta" 4100 4,
    Jugador "Pellosso" 2100 2,
    Jugador "Julio" 2200 2,
    Jugador "Capi" 3000 3,
    --Athletico Bilbao
    Jugador "Williams" 4200 6,
    Jugador "Capa" 3000 4,
    Jugador "Garcia" 2800 4,
    Jugador "Vesga" 2100 2,
    Jugador "Balenziaga" 2000 2,
    --Barcelona
    Jugador "Messi" 5000 7,
    Jugador "Fati" 3800 5,
    Jugador "Dest" 2500 3,
    Jugador "Griezmann" 2800 4,
    Jugador "Roberto" 2100 3,
    Jugador "Trincao" 1700 2,
    Jugador "Umtiti" 2000 3,
    --Real Madrid
    Jugador "Courtois" 4800 7,
    Jugador "Casemiro" 3800 5,
    Jugador "Mendy" 2700 5,
    Jugador "Nacho" 2700 5,
    Jugador "Asencio" 2300 4,
    Jugador "Militao" 2100 4,
    Jugador "Isco" 2400 5,
    Jugador "Jovic" 1900 2,
    --Athletico Madrid
    Jugador "Oblak" 4300 7,
    Jugador "Llorente" 2100 4,
    Jugador "Trippier" 2500 4,
    Jugador "Lodi" 2800 5,
    Jugador "Suarez" 3100 6,
    Jugador "Koke" 3100 5,
    Jugador "Lemar" 2500 4,
    Jugador "Savic" 2100 3,
    --Sevilla 
    Jugador "Navas" 2100 3,
    Jugador "Rakitic" 3000 6,
    Jugador "Kounde" 2300 4,
    Jugador "Gomez" 1900 2,
    Jugador "Jong" 3000 5,
    Jugador "Vidal" 1700 2,
    --Betis
    Jugador "Emerson" 3500 5,
    Jugador "Fekir" 3200 5,
    Jugador "Bravo" 2500 3,
    Jugador "Guardado" 2100 2,
    Jugador "Iglesias" 2500 4,
    Jugador "Bartra" 1900 2,
    Jugador "Joaquin" 2700 4,
    --Valencia
    Jugador "Cillesen" 2500 3,
    Jugador "Paulista" 3500 5,
    Jugador "Wass" 2800 4,
    Jugador "Gameiro" 2400 3,
    Jugador "Guedes" 2300 3,
    --Tokio F.C
    Jugador "Oliveira" 3500 5,
    Jugador "Hatano" 2900 4,
    Jugador "Abe" 2100 2,
    Jugador "Aoki" 1900 2,
    Jugador "Nagai" 2200 3,
    --Yokohama
    Jugador "Seko" 2200 3,
    Jugador "Kleber" 2500 4,
    Jugador "Takagi" 2300 4,
    Jugador "Takeda" 1600 2,
    Jugador "Takahashi" 2000 2,
    Jugador "Germain" 2300 3,
    --Kawasaki
    Jugador "Yamane" 3100 5,
    Jugador "Damiao" 3600 5,
    Jugador "Tanaka" 2900 4,
    Jugador "Taniguchi" 2500 3,
    Jugador "Ienaga" 2600 4,
    Jugador "Kobayashi" 3000 5,
    --River Plate
    Jugador "Alvarez" 2300 3,
    Jugador "Casco" 1900 2,
    Jugador "Montiel" 3000 4,
    Jugador "Armani" 3100 5,
    Jugador "Martinez" 2100 2,
    Jugador "Peña" 2200 2,
    --Boca Juniors
    Jugador "Izquierdoz" 2100 2,
    Jugador "Zambrano" 1700 2,
    Jugador "Mas" 2000 2,
    Jugador "Villa" 3000 4,
    Jugador "Tevez" 2500 3,
    --Flamengo
    Jugador "Islas" 2600 4,
    Jugador "Pedro" 2500 4,
    Jugador "Ribeiro" 2100 2,
    Jugador "Henrique" 2900 5,
    Jugador "Muniz" 3000 5,
    --Corinthians
    Jugador "Cassio" 2300 3,
    Jugador "Mosquito" 2400 4,
    Jugador "Cantillo" 2100 2,
    Jugador "Augusto" 1700 2,
    Jugador "Budiga" 2300 3,
    --Sao Paulo
    Jugador "Shaylo" 1500 2,
    Jugador "Rigoni" 3000 5,
    Jugador "Eder" 2500 3,
    Jugador "Nestor" 2100 2,
    Jugador "Pele" 2300 2,
    Jugador "Alves" 2500 3,
    --Santos
    Jugador "Felipe" 2800 4,
    Jugador "Nelson" 2100 2,
    Jugador "Marinho" 2700 4,
    Jugador "Mota" 2000 2,
    --Tolima
    Jugador "Mosquera" 3000 5,
    Jugador "Campaz" 2800 4,
    Jugador "Plata" 2500 4,
    Jugador "Caicedo" 2300 3,
    Jugador "Perez" 1500 2,
    --Millonarios
    Jugador "Arango" 2700 5,
    Jugador "Uribe" 2600 5,
    Jugador "Moreno" 2100 3,
    Jugador "Bertel" 2300 4,
    Jugador "Murillo" 1700 2,
    --Junior
    Jugador "Viera" 2300 4,
    Jugador "Borja" 2300 4,
    Jugador "Cetre" 2000 3,
    Jugador "Moreno" 1900 2,
    --Jiangsu
    Jugador "Xi" 2300 3,
    Jugador "Teixeira" 3000 5,
    Jugador "Eder" 2900 5,
    Jugador "Santitni" 2100 2,
    --Shanghai
    Jugador "Jinhao" 2900 4,
    Jugador "Xinli" 2500 3,
    Jugador "Moreno" 2100 3,
    --Manchester City
    Jugador "Dias" 3100 5,
    Jugador "Mahrez" 3900 6,
    Jugador "Torres" 2800 4,
    Jugador "Ake" 2300 3,
    Jugador "Rodri" 3000 5,
    --Manchester Unite
    Jugador "Fernandez" 3400 5,
    Jugador "Fred" 2500 4,
    Jugador "Gea" 3700 6,
    Jugador "Telles" 2500 3,
    --Chelsea 
    Jugador "Mount" 3000 5,
    Jugador "Chiwell" 3100 5,
    Jugador "Werner" 3800 6,
    Jugador "Ziyech" 2500 4,
    --Internazionale
    Jugador "Lukaku" 3400 6,
    Jugador "Sanchez" 2300 4,
    Jugador "Vecino" 2500 4,
    --Juventus
    Jugador "Danilo" 2100 3,
    Jugador "Ronaldo" 2400 4,
    Jugador "Sandro" 3000 5,
    Jugador "Costa" 2800 5,
    --AC Milan
    Jugador "Ibrahimovic" 3000 5,
    Jugador "Leao" 2300 3,
    Jugador "Donnarumma" 3100 5]

type Ubicaciones = [(ObjetoNombre,Estado)]
ubicaciones::Ubicaciones
ubicaciones = [
    ("Capi", "Mi Equipo"),

    ("CocaCola", "AeropuertoColombia"),
    ("Adidas","AeropuertoChina"),
    ("FlyEmirates","Club Real Madrid"),
    ("EASport","Playa Brasil"),
    ("Ford","Mercado Argentina"),
    ("Nike","Ciudad de Milan"),
    ("Rakuten","Plaza Tokio"),
    ("Audi","Ciudad Londres"),

    ("Manager", "Mi Club Oficina director"),
    -------------------------------------------------------
    --("Athletico Bilbao manager","Athletico Bilbao oficina manager"),
    ("Williams","Athletico Bilbao oficina manager"),
    ("Capa","Athletico Bilbao oficina manager"),
    ("Garcia","Athletico Bilbao oficina manager"),
    ("Vesga","Athletico Bilbao oficina manager"),
    ("Balenziaga","Athletico Bilbao oficina manager"),

    --("Barcelona manager","Barcelona oficina manager"),
    ("Messi","Barcelona oficina manager"),
    ("Fati","Barcelona oficina manager"),
    ("Dest","Barcelona oficina manager"),
    ("Griezmann","Barcelona oficina manager"),
    ("Roberto","Barcelona oficina manager"),
    ("Trincao","Barcelona oficina manager"),
    ("Umtiti","Barcelona oficina manager"),

    --("Real Madrid manager","Real Madrid oficina manager"),
    ("Courtois","Real Madrid oficina manager"),
    ("Casemiro","Real Madrid oficina manager"),
    ("Mendy","Real Madrid oficina manager"),
    ("Nacho","Real Madrid oficina manager"),
    ("Asencio","Real Madrid oficina manager"),
    ("Militao","Real Madrid oficina manager"),
    ("Isco","Real Madrid oficina manager"),
    ("Jovic","Real Madrid oficina manager"),

    --("Athletico de Madrid manager","Athletico de Madrid oficina manager"),
    ("Oblak","Athletico de Madrid oficina manager"),
    ("Llorente","Athletico de Madrid oficina manager"),
    ("Trippier","Athletico de Madrid oficina manager"),
    ("Lodi","Athletico de Madrid oficina manager"),
    ("Suarez","Athletico de Madrid oficina manager"),
    ("Koke","Athletico de Madrid oficina manager"),
    ("Lemar","Athletico de Madrid oficina manager"),
    ("Savic","Athletico de Madrid oficina manager"),

    --("Sevilla manager","Sevilla oficina manager"),
    ("Navas","Sevilla oficina manager"),
    ("Rakitic","Sevilla oficina manager"),
    ("Kounde","Sevilla oficina manager"),
    ("Gomez","Sevilla oficina manager"),
    ("Jong","Sevilla oficina manager"),
    ("Vidal","Sevilla oficina manager"),

    --("Betis manager","Betis oficina manager"),
    ("Emerson","Betis oficina manager"),
    ("Fekir","Betis oficina manager"),
    ("Bravo","Betis oficina manager"),
    ("Guardado","Betis oficina manager"),
    ("Iglesias","Betis oficina manager"),
    ("Bartra","Betis oficina manager"),
    ("Joaquin","Betis oficina manager"),

    --("Valencia manager","Valencia oficina manager"),
    ("Cillesen","Valencia oficina manager"),
    ("Paulista","Valencia oficina manager"),
    ("Wass","Valencia oficina manager"),
    ("Gameiro","Valencia oficina manager"),
    ("Guedes","Valencia oficina manager"),

    --("Tokio F.C manager","Tokio F.C oficina manager"),
    ("Oliveira","Tokio F.C oficina manager"),
    ("Hatano","Tokio F.C oficina manager"),
    ("Abe","Tokio F.C oficina manager"),
    ("Aoki","Tokio F.C oficina manager"),
    ("Nagai","Tokio F.C oficina manager"),

    --("Yokohama manager","Yokohama oficina manager"),
    ("Seko","Yokohama oficina manager"),
    ("Kleber","Yokohama oficina manager"),
    ("Takagi","Yokohama oficina manager"),
    ("Takeda","Yokohama oficina manager"),
    ("Takahashi","Yokohama oficina manager"),
    ("Germain","Yokohama oficina manager"),

    --("Kawasaki manager","Kawasaki oficina manager"),
    ("Yamane","Kawasaki oficina manager"),
    ("Damiao","Kawasaki oficina manager"),
    ("Tanaka","Kawasaki oficina manager"),
    ("Taniguchi","Kawasaki oficina manager"),
    ("Ienaga","Kawasaki oficina manager"),
    ("Kobayashi","Kawasaki oficina manager"),

    --("River Plate manager","River Plate oficina manager"),
    ("Alvarez","River Plate oficina manager"),
    ("Casco","River Plate oficina manager"),
    ("Montiel","River Plate oficina manager"),
    ("Armani","River Plate oficina manager"),
    ("Martinez","River Plate oficina manager"),
    ("Peña","River Plate oficina manager"),

    --("Boca Juniors manager","Boca Juniors oficina manager"),
    ("Izquierdoz","Boca Juniors oficina manager"),
    ("Mas","Boca Juniors oficina manager"),
    ("Zambrano","Boca Juniors oficina manager"),
    ("Villa","Boca Juniors oficina manager"),
    ("Tevez","Boca Juniors oficina manager"),

    --("Flamengo manager","Flamengo oficina manager"),
    ("Islas","Flamengo oficina manager"),
    ("Pedro","Flamengo oficina manager"),
    ("Ribeiro","Flamengo oficina manager"),
    ("Henrique","Flamengo oficina manager"),
    ("Muniz","Flamengo oficina manager"),

    --("Corinthians manager","Corinthians oficina manager"),
    ("Cassio","Corinthians oficina manager"),
    ("Mosquito","Corinthians oficina manager"),
    ("Cantillo","Corinthians oficina manager"),
    ("Augusto","Corinthians oficina manager"),
    ("Budiga","Corinthians oficina manager"),

    --("Sao Paulo manager","Sao Paulo oficina manager"),
    ("Shaylo","Sao Paulo oficina manager"),
    ("Rigoni","Sao Paulo oficina manager"),
    ("Eder","Sao Paulo oficina manager"),
    ("Nestor","Sao Paulo oficina manager"),
    ("Pele","Sao Paulo oficina manager"),
    ("Alves","Sao Paulo oficina manager"),

    --("Santos manager","Santos oficina manager"),
    ("Felipe","Santos oficina manager"),
    ("Nelson","Santos oficina manager"),
    ("Marinho","Santos oficina manager"),
    ("Mota","Santos oficina manager"),

    --("Tolima manager","Tolima oficina manager"),
    ("Mosquera","Tolima oficina manager"),
    ("Campaz","Tolima oficina manager"),
    ("Plata","Tolima oficina manager"),
    ("Caicedo","Tolima oficina manager"),
    ("Perez","Tolima oficina manager"),

    --("Millonarios manager","Millonarios oficina manager"),
    ("Arango","Millonarios oficina manager"),
    ("Uribe","Millonarios oficina manager"),
    ("Moreno","Millonarios oficina manager"),
    ("Bertel","Millonarios oficina manager"),
    ("Murillo","Millonarios oficina manager"),

    --("manager","Junior oficina manager"),
    ("Viera","Junior oficina manager"),
    ("Borja","Junior oficina manager"),
    ("Cetre","Junior oficina manager"),
    ("Moreno","Junior oficina manager"),
    
    --("Jiangsu manager","Jiangsu oficina manager"),
    ("Xi","Jiangsu oficina manager"),
    ("Teixeira","Jiangsu oficina manager"),
    ("Eder","Jiangsu oficina manager"),
    ("Santitni","Jiangsu oficina manager"),
    
    --("Shanghai manager","Shanghai oficina manager"),
    ("Jinhao","Shanghai oficina manager"),
    ("Xinli","Shanghai oficina manager"),
    ("Moreno","Shanghai oficina manager"),

    --("Manchester City manager","Manchester City oficina manager"),
    ("Dias","Manchester City oficina manager"),
    ("Mahrez","Manchester City oficina manager"),
    ("Torres","Manchester City oficina manager"),
    ("Ake","Manchester City oficina manager"),
    ("Rodri","Manchester City oficina manager"),
    
    --("Manchester United manager","Manchester United oficina manager"),
    ("Fernandez","Manchester United oficina manager"),
    ("Fred","Manchester United oficina manager"),
    ("Gea","Manchester United oficina manager"),
    ("Telles","Manchester United oficina manager"),
    
    --("Chelsea manager","Chelsea oficina manager"),
    ("Mount","Chelsea oficina manager"),
    ("Chiwell","Chelsea oficina manager"),
    ("Werner","Chelsea oficina manager"),
    ("Ziyech","Chelsea oficina manager"),
    
    --("Internazionale manager","Internazionale oficina manager"),
    ("Lukaku","Internazionale oficina manager"),
    ("Sanchez","Internazionale oficina manager"),
    ("Vecino","Internazionale oficina manager"),
    
    --("Juventus manager","Juventus oficina manager"),
    ("Danilo","Juventus oficina manager"),
    ("Ronaldo","Juventus oficina manager"),
    ("Sandro","Juventus oficina manager"),
    ("Costa","Juventus oficina manager"),
    
    --("AC Milan manager","AC Milan oficina manager"),
    ("Ibrahimovic","AC Milan oficina manager"),
    ("Leao","AC Milan oficina manager"),
    ("Donnarumma","AC Milan oficina manager")]